2017-07-31 13:06:27,118 [Thread-2:140415120647936] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-07-31 13:06:27,852 [Thread-3:140415112255232] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-07-31 13:06:59,494 [Thread-105:140414887651072] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 13:10:04,184 [Thread-12:140396605445888] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 13:12:56,491 [Thread-2:140436299306752] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 13:18:35,163 [Thread-2:140526948173568] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 13:18:39,831 [Thread-3:140526939780864] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-07-31 13:21:32,145 [Thread-32:140526939780864] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 13:22:27,312 [Thread-3:140555572459264] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 13:22:36,566 [Thread-2:140354057611008] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 13:22:38,723 [Thread-3:140354049218304] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 13:35:26,078 [Thread-40:140497548199680] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /admin/blog/propic/add/
2017-07-31 13:36:35,934 [Thread-49:140497531414272] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /admin/blog/propic/add/
2017-07-31 13:44:52,620 [Thread-152:140497556592384] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /admin/shop/product_desc/add/
2017-07-31 13:50:22,333 [Thread-193:140497523021568] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /admin/shop/shopsales/add/
2017-07-31 13:54:26,900 [Thread-238:140497171511040] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /admin/shop/shopsales/add/
2017-07-31 13:57:47,414 [Thread-265:140497531414272] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /admin/shop/product_desc/add/
2017-07-31 14:07:26,754 [Thread-447:140497548199680] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /admin/login/
2017-07-31 14:23:06,999 [Thread-39:140599017588480] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:27:21,267 [Thread-20:139644372735744] [django.request:182] [base:get_response] [WARNING]- Not Found: /uploads/avatar/default.png
2017-07-31 14:28:14,759 [Thread-51:140599009195776] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /reg/
2017-07-31 14:28:21,391 [Thread-52:140599042766592] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /reg/
2017-07-31 14:28:42,709 [Thread-58:140599025981184] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:36:22,778 [Thread-2:140008727951104] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 14:36:24,582 [Thread-3:140008727951104] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 14:36:26,622 [Thread-4:140008727951104] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 14:36:32,318 [Thread-9:140008718509824] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:37:50,151 [Thread-12:140008727951104] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:40:32,782 [Thread-2:139797180532480] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:44:23,386 [Thread-3:139886846347008] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:44:30,596 [Thread-8:139886846347008] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:44:53,253 [Thread-15:139886480848640] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:45:17,842 [Thread-22:139886854739712] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_login didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:45:40,538 [Thread-33:139886829299456] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 14:45:42,159 [Thread-34:139886837954304] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 14:45:43,453 [Thread-35:139886480848640] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 14:45:52,378 [Thread-39:139886464063232] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog/blog_video
2017-07-31 14:46:00,638 [Thread-43:139886464063232] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:46:23,354 [Thread-44:139886464063232] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:46:24,603 [Thread-2:140226263791360] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:46:25,213 [Thread-3:140226263791360] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:46:25,949 [Thread-4:140226185918208] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:46:26,444 [Thread-5:140226177525504] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:46:46,388 [Thread-8:140226169132800] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/phone_auth/views.py", line 113, in do_logout
    return HttpResponseRedirect(reverse(index))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'phone_auth.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-07-31 14:46:47,236 [Thread-2:139981863405312] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_logout didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:46:47,964 [Thread-3:139981863405312] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_logout didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:46:48,437 [Thread-4:139981863405312] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_logout didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:48:35,299 [Thread-5:139981863405312] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view phone_auth.views.do_logout didn't return an HttpResponse object. It returned None instead.
2017-07-31 14:48:58,708 [Thread-2:140364723975936] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 14:56:54,130 [Thread-37:140364715583232] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /login/
2017-07-31 15:13:08,062 [Thread-2:140549889431296] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-07-31 15:13:12,975 [Thread-3:140549881038592] [django.request:182] [base:get_response] [WARNING]- Not Found: /video
2017-07-31 15:13:43,344 [Thread-9:140549872645888] [django.request:182] [base:get_response] [WARNING]- Not Found: /video
2017-07-31 15:13:50,528 [Thread-4:139763188020992] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:14:59,620 [Thread-7:139763179104000] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:15:07,091 [Thread-6:140025644697344] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:15:10,279 [Thread-8:140025644697344] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:15:13,001 [Thread-10:140025644697344] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:15:15,202 [Thread-12:140025644697344] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:15:18,402 [Thread-14:140025635518208] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:18:31,153 [Thread-24:140025644697344] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:19:45,838 [Thread-29:140025626863360] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:20:12,914 [Thread-31:140025644697344] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:20:13,424 [Thread-33:140025626863360] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:20:15,361 [Thread-35:140025644697344] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/mi4.png
2017-07-31 15:29:39,504 [Thread-16:139703844058880] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:29:45,519 [Thread-20:139703877629696] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:29:48,854 [Thread-23:139703954532096] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:30:23,830 [Thread-29:139703860844288] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:30:25,879 [Thread-30:139703877629696] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:37:52,084 [Thread-68:139703877629696] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:37:56,649 [Thread-69:139703844058880] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:38:50,449 [Thread-77:139703877629696] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/player.swf
2017-07-31 15:51:42,753 [Thread-18:139789156210432] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 1043, in render
    output = self.filter_expression.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaultfilters.py", line 615, in slice_filter
    for x in arg.split(':'):
AttributeError: 'int' object has no attribute 'split'
2017-07-31 15:54:25,228 [Thread-22:139789172995840] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_MuZYCcM.jpg
2017-07-31 15:54:25,228 [Thread-21:139789147817728] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product.jpg
2017-07-31 15:54:25,229 [Thread-20:139789164603136] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5big1_kQPVdRx.jpg
2017-07-31 15:54:25,232 [Thread-23:139789139425024] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_EE0zJKr.jpg
2017-07-31 15:54:29,889 [Thread-26:139789147817728] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product.jpg
2017-07-31 15:54:29,897 [Thread-28:139789172995840] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_EE0zJKr.jpg
2017-07-31 15:54:29,899 [Thread-27:139789164603136] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_MuZYCcM.jpg
2017-07-31 15:54:29,900 [Thread-25:139789139425024] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5big1_kQPVdRx.jpg
2017-07-31 15:54:30,509 [Thread-30:139789139425024] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5big1_kQPVdRx.jpg
2017-07-31 15:54:30,517 [Thread-31:139789164603136] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product.jpg
2017-07-31 15:54:30,528 [Thread-32:139789172995840] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_MuZYCcM.jpg
2017-07-31 15:54:30,531 [Thread-33:139789147817728] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_EE0zJKr.jpg
2017-07-31 15:54:49,409 [Thread-37:139789172995840] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5big1_kQPVdRx.jpg
2017-07-31 15:54:49,413 [Thread-40:139789139425024] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_EE0zJKr.jpg
2017-07-31 15:54:49,418 [Thread-38:139789164603136] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product.jpg
2017-07-31 15:54:49,438 [Thread-39:139789156210432] [django.request:182] [base:get_response] [WARNING]- Not Found: /blog_video/blog/video/2017/07/5product_MuZYCcM.jpg
2017-07-31 15:55:31,889 [Thread-41:139789164603136] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:55:33,183 [Thread-42:139789156210432] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:55:33,993 [Thread-43:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:55:34,814 [Thread-44:139789172995840] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:56:20,165 [Thread-51:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:56:21,298 [Thread-52:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:56:45,688 [Thread-57:139789172995840] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:56:46,608 [Thread-58:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:56:57,173 [Thread-60:139789172995840] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '=>' from '=>'
2017-07-31 15:56:57,857 [Thread-61:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '=>' from '=>'
2017-07-31 15:56:58,121 [Thread-62:139789172995840] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '=>' from '=>'
2017-07-31 15:56:58,340 [Thread-63:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '=>' from '=>'
2017-07-31 15:58:45,062 [Thread-65:139789172995840] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 15:58:45,928 [Thread-66:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:00:48,277 [Thread-77:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:00:49,135 [Thread-78:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:00:49,630 [Thread-79:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:01:50,158 [Thread-86:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:01:51,192 [Thread-87:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:01:51,901 [Thread-88:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:03:12,739 [Thread-96:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:04:03,354 [Thread-101:139789147817728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:04:04,697 [Thread-102:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:04:59,627 [Thread-108:139789139425024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:05:50,456 [Thread-154:139789156210432] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:05:52,520 [Thread-155:139789156210432] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:05:53,138 [Thread-156:139789172995840] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/templatetags/static.py", line 103, in render
    url = self.url(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 15, in url
    path = self.path.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 68, in _get_url
    self._require_file()
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 46, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'img_url' attribute has no file associated with it.
2017-07-31 16:13:07,100 [Thread-2:140309477472000] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog_video/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 53, in blog_video
    return render(request,'blog_video.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'video' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['video/(?P<id>\\d+)/$']
2017-07-31 16:27:40,466 [Thread-43:140222883464960] [django.request:182] [base:get_response] [WARNING]- Not Found: /video/3/<embed src='http://player.youku.com/player.php/sid/XMjgzODUxNjUwOA==/v.swf' allowFullScreen='true' quality='high' width='480' height='400' align='middle' allowScriptAccess='always' type='application/x
2017-07-31 16:41:09,346 [Thread-2:140266666424064] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-07-31 16:41:16,722 [Thread-4:140266577061632] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: article_details() got an unexpected keyword argument 'id'
2017-07-31 16:41:25,879 [Thread-8:140266666424064] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details
2017-07-31 16:41:38,294 [Thread-9:140266666424064] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details
2017-07-31 16:50:53,074 [Thread-17:140185367799552] [django.request:182] [base:get_response] [WARNING]- Not Found: /article
2017-07-31 17:02:27,344 [Thread-2:140210098382592] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details/
2017-07-31 17:02:28,011 [Thread-3:140210089989888] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details/
2017-07-31 17:02:28,396 [Thread-4:140209878464256] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details/
2017-07-31 17:02:28,811 [Thread-5:140209870071552] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details/
2017-07-31 17:02:29,078 [Thread-6:140209861678848] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details/
2017-07-31 17:02:30,753 [Thread-7:140209853286144] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: article_details() got an unexpected keyword argument 'id'
2017-07-31 17:02:50,669 [Thread-10:140209853286144] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: article_details() got an unexpected keyword argument 'id'
2017-07-31 17:02:51,874 [Thread-2:139948481378048] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: type object 'Http404' has no attribute 'get'
2017-07-31 17:02:52,754 [Thread-3:139948481378048] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: type object 'Http404' has no attribute 'get'
2017-07-31 17:02:53,240 [Thread-4:139948481378048] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: type object 'Http404' has no attribute 'get'
2017-07-31 17:02:53,714 [Thread-5:139948481378048] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: type object 'Http404' has no attribute 'get'
2017-07-31 17:02:55,080 [Thread-6:139948481378048] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: type object 'Http404' has no attribute 'get'
2017-07-31 17:04:34,201 [Thread-7:139948481378048] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /article_details/1/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: type object 'Http404' has no attribute 'get'
2017-07-31 17:04:43,361 [Thread-7:140445563746048] [django.request:182] [base:get_response] [WARNING]- Not Found: /article
2017-07-31 17:04:43,804 [Thread-8:140445563746048] [django.request:182] [base:get_response] [WARNING]- Not Found: /article
2017-07-31 17:17:50,313 [Thread-2:140376796788480] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 43, in blog
    return render(request,'blog.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 40, in get_template
    contents = self.get_contents(origin)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/filesystem.py", line 24, in get_contents
    with io.open(origin.name, encoding=self.engine.file_charset) as fp:
IOError: [Errno 21] Is a directory: u'/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/admin/templates'
2017-07-31 17:17:50,783 [Thread-3:140376796788480] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 43, in blog
    return render(request,'blog.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 40, in get_template
    contents = self.get_contents(origin)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/filesystem.py", line 24, in get_contents
    with io.open(origin.name, encoding=self.engine.file_charset) as fp:
IOError: [Errno 21] Is a directory: u'/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/admin/templates'
2017-07-31 17:17:51,817 [Thread-4:140376711100160] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 43, in blog
    return render(request,'blog.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 40, in get_template
    contents = self.get_contents(origin)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/filesystem.py", line 24, in get_contents
    with io.open(origin.name, encoding=self.engine.file_charset) as fp:
IOError: [Errno 21] Is a directory: u'/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/admin/templates'
2017-07-31 17:17:52,514 [Thread-5:140376702707456] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/
Traceback (most recent call last):
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jinuo/Django/XphoneProject/blog/views.py", line 43, in blog
    return render(request,'blog.html',locals())
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 40, in get_template
    contents = self.get_contents(origin)
  File "/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/template/loaders/filesystem.py", line 24, in get_contents
    with io.open(origin.name, encoding=self.engine.file_charset) as fp:
IOError: [Errno 21] Is a directory: u'/home/jinuo/myvenv/local/lib/python2.7/site-packages/django/contrib/admin/templates'
2017-07-31 17:18:50,975 [Thread-47:140376796788480] [django.request:182] [base:get_response] [WARNING]- Not Found: /article
2017-07-31 17:18:56,475 [Thread-53:140376711100160] [django.request:182] [base:get_response] [WARNING]- Not Found: /article_details/
